return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      -- preset = "modern",
      preset = "helix",
      --     defaults = {
      --       ["<leader>a"] = { name = "+  CopilotChat", mode = { "n", "v", "x" } },
      --       ["<leader>b"] = { name = "+  Buffer", mode = "n" },
      --       ["<leader>c"] = { name = "+  Code", mode = { "n", "x" } },
      --       ["<leader>d"] = { name = "+  Debug", mode = { "n", "x" } },
      --       ["<leader>f"] = { name = "+ 󰈞 File/Find", mode = "n" },
      --       ["<leader>g"] = { name = "+  Git", mode = { "n", "x" } },
      --       ["<leader>m"] = { name = "+  Markdown", mode = "n" },
      --       ["<leader>s"] = { name = "+  Search", mode = { "n", "x" } },
      --       ["<leader>u"] = { name = "+ 󰔃 UI", mode = "n" },
      --       ["<leader>W"] = { name = "+  Window", mode = "n" },
      --       ["<leader>q"] = { name = "+ 󰩈 Quit/Session", mode = "n" },
      --       ["<leader>x"] = { name = "+ 󰁨 Diagnostics/QuickFix", mode = { "n", "x" } },
      --       ["<leader><tab>"] = { name = "+  Tab", mode = "n" },
      --       ["<leader>t"] = { name = "+  Test", mode = "n" },
      --       ["<leader>z"] = { name = "+  Telekasten", mode = "n" },

      --       ["<leader>"] = {
      --         w = { "<cmd>w<cr>", " Save" },
      -- },
      -- },
    },

    keys = {
      -- { "<leader>wm", hidden = true },
      -- { "<leader>cal", hidden = true },
      -- { "<leader>caL", hidden = true },
      -- { "<leader>w", hidden = true },
      -- { "<leader>w", icon = { icon = "" }, group = "Write" },
      -- { "<leader>z", icon = { icon = "" }, group = "Telekasten" },
      -- { "<leader>m", group = "Markdown" },
    },
    -- config = function()
    --     -- ["<leader>a"] = { name = "+  CopilotChat", mode = { "n", "v", "x" } },
    --     -- ["<leader>b"] = { name = "+  Buffer", mode = "n" },
    --     -- ["<leader>c"] = { name = "+  Code", mode = { "n", "x" } },
    --     -- ["<leader>d"] = { name = "+  Debug", mode = { "n", "x" } },
    --     -- ["<leader>f"] = { name = "+ 󰈞 File/Find", mode = "n" },
    --     -- ["<leader>g"] = { name = "+  Git", mode = { "n", "x" } },
    --     -- ["<leader>m"] = { name = "+  Markdown", mode = "n" },
    --     -- ["<leader>s"] = { name = "+  Search", mode = { "n", "x" } },
    --     -- ["<leader>u"] = { name = "+ 󰔃 UI", mode = "n" },
    --     -- ["<leader>W"] = { name = "+  Window", mode = "n" },
    --     -- ["<leader>q"] = { name = "+ 󰩈 Quit/Session", mode = "n" },
    --     -- ["<leader>x"] = { name = "+ 󰁨 Diagnostics/QuickFix", mode = { "n", "x" } },
    --     -- ["<leader><tab>"] = { name = "+  Tab", mode = "n" },
    --     -- ["<leader>t"] = { name = "+  Test", mode = "n" },
    --     -- ["<leader>z"] = { name = "+  Telekasten", mode = "n" },
    --   })
    -- end,
    -- },
  },
}
